defaults:
  - annotation: activity-1s
  - stream: atr-acc-all # set filename that you created in the previous step. 
  - split: openpack-challenge-2022
  - classes: OPENPACK_OPERATIONS
name: "atr-acc" # set dataset config name. This value will be included in the log directory path.