version: "3.9"
services:
  app:
    build: .

    container_name: openpack
    hostname: openpack

    network_mode: "host"
    volumes:
      - ../:/workspace
    working_dir: /workspace
    shm_size: 256gb
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ['0']
              capabilities: [ gpu ]
